apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: notifications.events.hatobatsugu.gsc
spec:
  group: events.hatobatsugu.gsc
  scope: Namespaced
  names:
    plural: notifications
    singular: notification
    kind: Notification
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                tpl:
                  type: string
                filter:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      key:
                        type: string
                      val:
                        type: string
                engine:
                  type: string